name: "Bug report"
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue :pray:.

        Please read our [guidelines to report issues](https://github.com/nxpkg/webcontainer-core/blob/main/repro.md).

        This issue tracker is for bugs and issues found within WebContainer.
        If you experience issues unrelated to WebContainer, please file an issue in our NxPKG core repo. https://github.com/nxpkg/core

        The more information you fill in, the better we can help you.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of what you're running into.
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link to the blitz that caused the error
      description: Please do not delete it after reporting!
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Describe the steps we have to take to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Provide a clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: checkboxes
    id: local-verification
    attributes:
      label: Parity with Local
      description: Does the issue appear only when running the WebContainer project? Or does it also appear locally?
      options:
        - label: I have [run the project in my local machine](https://github.com/nxpkg/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.
          required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: textarea
    id: platform
    attributes:
      label: Platform
      value: |
        - OS: [e.g. macOS, Windows, Linux]
        - Browser: [e.g. Chrome, Safari, Firefox]
        - Version: [e.g. 91.1]
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.